"use client";
import {useEffect,useMemo,useState} from "react";
import {createVisualDocument,visualBindings,type VisualDocument,type VisualElement} from "@/lib/visual-engine";
import {saveVisualTemplate} from "@/app/app/editor-visual/actions";

const seed=():VisualDocument=>({...createVisualDocument("Rascunho visual"),elements:[
 {id:"product",type:"text",name:"Produto",visible:true,locked:false,binding:"product.name",transform:{x:70,y:90,width:500,height:90,rotation:0,opacity:1,layer:2},textStyle:{fontSize:56,fontWeight:800,color:"#111111",textAlign:"left"}},
 {id:"price",type:"text",name:"Preço",visible:true,locked:false,binding:"offer.price",transform:{x:610,y:690,width:350,height:160,rotation:0,opacity:1,layer:3},textStyle:{fontSize:110,fontWeight:900,color:"#111111",textAlign:"center"}},
]});

export function VisualEngineEditor({initialDocument,initialTemplateId,initialVersion}:{initialDocument?:VisualDocument;initialTemplateId?:string;initialVersion?:number}){
 const [doc,setDoc]=useState<VisualDocument>(()=>initialDocument??seed()); const [selected,setSelected]=useState("product"); const [history,setHistory]=useState<VisualDocument[]>([]); const [future,setFuture]=useState<VisualDocument[]>([]);
 const current=doc.elements.find(e=>e.id===selected);
 const ordered=useMemo(()=>[...doc.elements].sort((a,b)=>b.transform.layer-a.transform.layer),[doc.elements]);
 const [zoom,setZoom]=useState(67); const [snap,setSnap]=useState(true); const [guides,setGuides]=useState<{x?:number;y?:number}>({}); const [templateId,setTemplateId]=useState<string|null>(initialTemplateId??null); const [version,setVersion]=useState<number|null>(initialVersion??null); const [saving,setSaving]=useState(false); const [saveMessage,setSaveMessage]=useState("");
 useEffect(()=>{function keydown(event:KeyboardEvent){const target=event.target as HTMLElement|null;if(target&&["INPUT","TEXTAREA","SELECT"].includes(target.tagName))return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="z"){event.preventDefault();event.shiftKey?redo():undo();return}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="d"){event.preventDefault();duplicate();return}if((event.key==="Delete"||event.key==="Backspace")&&current){event.preventDefault();remove();return}if(current&&!current.locked&&["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(event.key)){event.preventDefault();const step=event.shiftKey?10:1;const dx=event.key==="ArrowLeft"?-step:event.key==="ArrowRight"?step:0;const dy=event.key==="ArrowUp"?-step:event.key==="ArrowDown"?step:0;patch({transform:{...current.transform,x:current.transform.x+dx,y:current.transform.y+dy}})}}window.addEventListener("keydown",keydown);return()=>window.removeEventListener("keydown",keydown)})
 function rotatePointer(event:React.PointerEvent<HTMLButtonElement>,element:VisualElement){if(element.locked)return;event.preventDefault();event.stopPropagation();const box=event.currentTarget.parentElement?.getBoundingClientRect();if(!box)return;const cx=box.left+box.width/2,cy=box.top+box.height/2;let moved=false;const angle=(x:number,y:number)=>Math.atan2(y-cy,x-cx)*180/Math.PI+90;const offset=element.transform.rotation-angle(event.clientX,event.clientY);const onMove=(e:PointerEvent)=>{moved=true;let rotation=angle(e.clientX,e.clientY)+offset;if(e.shiftKey)rotation=Math.round(rotation/15)*15;setDoc(d=>({...d,elements:d.elements.map(item=>item.id===element.id?{...item,transform:{...item.transform,rotation:Math.round(rotation*10)/10}}:item)}))};const onUp=()=>{window.removeEventListener("pointermove",onMove);window.removeEventListener("pointerup",onUp);if(moved){setHistory(h=>[...h.slice(-49),doc]);setFuture([])}};window.addEventListener("pointermove",onMove);window.addEventListener("pointerup",onUp)}
 function resizePointer(event:React.PointerEvent<HTMLButtonElement>,element:VisualElement){if(element.locked)return;event.preventDefault();event.stopPropagation();const host=event.currentTarget.parentElement?.parentElement;if(!host)return;const startX=event.clientX,startY=event.clientY,start={width:element.transform.width,height:element.transform.height};const scaleX=doc.width/host.getBoundingClientRect().width,scaleY=doc.height/host.getBoundingClientRect().height;let moved=false;const onMove=(e:PointerEvent)=>{moved=true;setDoc(d=>({...d,elements:d.elements.map(item=>item.id===element.id?{...item,transform:{...item.transform,width:Math.max(10,start.width+(e.clientX-startX)*scaleX),height:Math.max(10,start.height+(e.clientY-startY)*scaleY)}}:item)}))};const onUp=()=>{window.removeEventListener("pointermove",onMove);window.removeEventListener("pointerup",onUp);if(moved){setHistory(h=>[...h.slice(-49),doc]);setFuture([])}};window.addEventListener("pointermove",onMove);window.addEventListener("pointerup",onUp)}
 function movePointer(event:React.PointerEvent<HTMLDivElement>,element:VisualElement){if(element.locked)return;event.preventDefault();event.stopPropagation();setSelected(element.id);const host=event.currentTarget.parentElement;if(!host)return;const startX=event.clientX,startY=event.clientY,start={x:element.transform.x,y:element.transform.y};const scaleX=doc.width/host.getBoundingClientRect().width,scaleY=doc.height/host.getBoundingClientRect().height;let moved=false;const onMove=(e:PointerEvent)=>{moved=true;let x=start.x+(e.clientX-startX)*scaleX,y=start.y+(e.clientY-startY)*scaleY;if(snap){x=Math.round(x/10)*10;y=Math.round(y/10)*10}const threshold=6;const centerX=(doc.width-element.transform.width)/2,centerY=(doc.height-element.transform.height)/2;let gx=Math.abs(x-centerX)<=threshold?doc.width/2:undefined,gy=Math.abs(y-centerY)<=threshold?doc.height/2:undefined;if(gx!==undefined)x=centerX;if(gy!==undefined)y=centerY;for(const other of doc.elements){if(other.id===element.id||!other.visible)continue;const xTargets=[other.transform.x,other.transform.x+other.transform.width/2,other.transform.x+other.transform.width];const yTargets=[other.transform.y,other.transform.y+other.transform.height/2,other.transform.y+other.transform.height];const ownX=[x,x+element.transform.width/2,x+element.transform.width],ownY=[y,y+element.transform.height/2,y+element.transform.height];outerX:for(let a=0;a<ownX.length;a++)for(const target of xTargets)if(Math.abs(ownX[a]-target)<=threshold){x+=target-ownX[a];gx=target;break outerX}outerY:for(let a=0;a<ownY.length;a++)for(const target of yTargets)if(Math.abs(ownY[a]-target)<=threshold){y+=target-ownY[a];gy=target;break outerY}}setGuides({x:gx,y:gy});setDoc(d=>({...d,elements:d.elements.map(item=>item.id===element.id?{...item,transform:{...item.transform,x,y}}:item)}))};const onUp=()=>{window.removeEventListener("pointermove",onMove);window.removeEventListener("pointerup",onUp);setGuides({});if(moved){setHistory(h=>[...h.slice(-49),doc]);setFuture([])}};window.addEventListener("pointermove",onMove);window.addEventListener("pointerup",onUp)}
 function commit(next:VisualDocument){setHistory(h=>[...h.slice(-49),doc]);setFuture([]);setDoc(next)}
 function patch(values:Partial<VisualElement>){if(!current)return;commit({...doc,elements:doc.elements.map(e=>e.id===current.id?{...e,...values}:e)})}
 function patchTransform(key:keyof VisualElement["transform"],value:number){if(!current||current.locked||!Number.isFinite(value))return;const next=key==="opacity"?Math.max(0,Math.min(1,value)):key==="layer"?Math.round(value):["width","height"].includes(key)?Math.max(1,value):value;patch({transform:{...current.transform,[key]:next}})}
 function align(axis:"left"|"centerX"|"right"|"top"|"centerY"|"bottom"){if(!current||current.locked)return;const t=current.transform;const next={...t};if(axis==="left")next.x=0;if(axis==="centerX")next.x=(doc.width-t.width)/2;if(axis==="right")next.x=doc.width-t.width;if(axis==="top")next.y=0;if(axis==="centerY")next.y=(doc.height-t.height)/2;if(axis==="bottom")next.y=doc.height-t.height;patch({transform:next})}
 function layer(delta:number){if(!current||current.locked)return;patchTransform("layer",Math.max(0,current.transform.layer+delta))}
 function remove(){if(!current||current.locked)return;commit({...doc,elements:doc.elements.filter(e=>e.id!==current.id)});setSelected("")}
 function duplicate(){if(!current)return;const id=`${current.id}-copy-${Date.now()}`;const copy={...current,id,name:`${current.name} (cópia)`,transform:{...current.transform,x:current.transform.x+20,y:current.transform.y+20,layer:doc.elements.length+1}};commit({...doc,elements:[...doc.elements,copy]});setSelected(id)}
 function add(type:VisualElement["type"]){const id=`${type}-${Date.now()}`;const next:VisualElement={id,type,name:type==="text"?"Novo texto":type==="image"?"Nova imagem":type==="barcode"?"Código de barras":type==="shape"?"Forma":"Grupo",visible:true,locked:false,transform:{x:100,y:100,width:260,height:100,rotation:0,opacity:1,layer:doc.elements.length+1},text:type==="text"?"Texto":undefined,textStyle:type==="text"?{fontSize:48,fontWeight:700,color:"#111111",textAlign:"left"}:undefined,shape:type==="shape"?{kind:"rectangle",fill:"#ffffff",stroke:"#111111",strokeWidth:1}:undefined};commit({...doc,elements:[...doc.elements,next]});setSelected(id)}
 function undo(){const prev=history.at(-1);if(!prev)return;setFuture(f=>[doc,...f]);setHistory(h=>h.slice(0,-1));setDoc(prev)}
 function redo(){const next=future[0];if(!next)return;setHistory(h=>[...h,doc]);setFuture(f=>f.slice(1));setDoc(next)}
 async function save(){setSaving(true);setSaveMessage("");try{const result=await saveVisualTemplate({templateId,name:doc.name,category:"custom",document:doc});setTemplateId(result.templateId);setVersion(result.version);setSaveMessage(`Salvo · versão ${result.version}`)}catch(error){setSaveMessage(error instanceof Error?error.message:"Falha ao salvar template.")}finally{setSaving(false)}}
 return <div style={{display:"grid",gridTemplateColumns:"220px minmax(0,1fr) 280px",gap:14,alignItems:"start"}}>
  <aside className="card"><strong>Elementos</strong><div style={{display:"grid",gap:6,marginTop:10}}>{ordered.map(e=><button key={e.id} className="btn" onClick={()=>setSelected(e.id)} style={{textAlign:"left",opacity:e.visible?1:.55}}>{e.locked?"🔒 ":""}{e.name}</button>)}</div><div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:12}}>{(["text","image","shape","barcode"] as const).map(t=><button key={t} className="btn" onClick={()=>add(t)}>+ {t}</button>)}</div></aside>
  <main><div className="preview-actions no-print" style={{marginBottom:10}}><button className="btn" disabled={!history.length} onClick={undo}>Desfazer</button><button className="btn" disabled={!future.length} onClick={redo}>Refazer</button><label className="muted"><input type="checkbox" checked={snap} onChange={e=>setSnap(e.target.checked)}/> Grade 10px</label><label className="muted">Zoom <input type="range" min="25" max="100" step="5" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/> {zoom}%</label><button className="btn" disabled={saving} onClick={save}>{saving?"Salvando…":"Salvar template"}</button><span className="muted">{saveMessage||`Prancheta ${doc.width} × ${doc.height}${version?` · v${version}`:""}`}</span></div>
   <div style={{position:"relative",width:`${zoom}%`,maxWidth:1080,margin:"0 auto",aspectRatio:`${doc.width}/${doc.height}`,backgroundColor:doc.background.color,backgroundImage:snap?"linear-gradient(to right, rgba(148,163,184,.18) 1px, transparent 1px),linear-gradient(to bottom, rgba(148,163,184,.18) 1px, transparent 1px)":"none",backgroundSize:snap?`${10/doc.width*100}% ${10/doc.height*100}%`:"auto",border:"1px solid var(--line)",overflow:"hidden"}}>
    {guides.x!==undefined&&<div style={{position:"absolute",left:`${(guides.x??0)/doc.width*100}%`,top:0,bottom:0,width:1,background:"#2563eb",zIndex:9999,pointerEvents:"none"}}/>}{guides.y!==undefined&&<div style={{position:"absolute",top:`${(guides.y??0)/doc.height*100}%`,left:0,right:0,height:1,background:"#2563eb",zIndex:9999,pointerEvents:"none"}}/>}
    {doc.elements.filter(e=>e.visible).sort((a,b)=>a.transform.layer-b.transform.layer).map(e=><div key={e.id} onPointerDown={event=>movePointer(event,e)} onClick={()=>setSelected(e.id)} style={{position:"absolute",cursor:e.locked?"default":"move",touchAction:"none",left:`${e.transform.x/doc.width*100}%`,top:`${e.transform.y/doc.height*100}%`,width:`${e.transform.width/doc.width*100}%`,height:`${e.transform.height/doc.height*100}%`,transform:`rotate(${e.transform.rotation}deg) skew(${e.transform.skewX??0}deg, ${e.transform.skewY??0}deg)`,opacity:e.transform.opacity,zIndex:e.transform.layer,border:e.id===selected?"2px solid #2563eb":"1px dashed #94a3b8",display:"grid",placeItems:"center",color:e.textStyle?.color,fontSize:`${Math.max(10,(e.textStyle?.fontSize??32)/doc.width*1080*zoom/100)}px`,fontWeight:e.textStyle?.fontWeight,textAlign:e.textStyle?.textAlign??"center",userSelect:"none"}}>
      {e.type==="text"?(e.text||e.binding||e.name):e.type==="image"?"Imagem":e.type==="barcode"?"||||| 789...":e.type==="shape"?"Forma":"Grupo"}
      {e.id===selected&&!e.locked&&<button type="button" aria-label="Rotacionar" onPointerDown={event=>rotatePointer(event,e)} style={{position:"absolute",left:"50%",top:-26,transform:"translateX(-50%)",width:14,height:14,borderRadius:"50%",padding:0,border:"2px solid white",background:"#2563eb",cursor:"grab",touchAction:"none"}}/>}
      {e.id===selected&&!e.locked&&<button type="button" aria-label="Redimensionar" onPointerDown={event=>resizePointer(event,e)} style={{position:"absolute",right:-7,bottom:-7,width:14,height:14,padding:0,border:"2px solid white",background:"#2563eb",cursor:"nwse-resize",touchAction:"none"}}/>}
    </div>)}
   </div>
  </main>
  <aside className="card"><strong>Propriedades</strong>{current?<div className="form" style={{marginTop:10}}><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button className="btn" type="button" onClick={duplicate}>Duplicar</button><button className="btn" type="button" disabled={current.locked} onClick={remove}>Excluir</button><button className="btn" type="button" disabled={current.locked} onClick={()=>layer(1)}>Frente</button><button className="btn" type="button" disabled={current.locked} onClick={()=>layer(-1)}>Trás</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:5}}>{([["left","Esq."],["centerX","Centro X"],["right","Dir."],["top","Topo"],["centerY","Centro Y"],["bottom","Base"]] as const).map(([axis,label])=><button key={axis} className="btn" type="button" disabled={current.locked} onClick={()=>align(axis)}>{label}</button>)}</div><label className="field"><span>Nome</span><input className="input" value={current.name} onChange={e=>patch({name:e.target.value})}/></label><div style={{display:"flex",gap:10}}><label><input type="checkbox" checked={current.visible} onChange={e=>patch({visible:e.target.checked})}/> Visível</label><label><input type="checkbox" checked={current.locked} onChange={e=>patch({locked:e.target.checked})}/> Bloqueado</label></div>
   {(["x","y","width","height","rotation","skewX","skewY","opacity","layer"] as const).map(k=><label className="field" key={k}><span>{k}</span><input className="input" type="number" step={k==="opacity"?.05:1} min={k==="opacity"?0:undefined} max={k==="opacity"?1:undefined} value={current.transform[k]??0} onChange={e=>patchTransform(k,Number(e.target.value))}/></label>)}
   {current.type==="text"&&<><label className="field"><span>Texto livre</span><input className="input" value={current.text??""} onChange={e=>patch({text:e.target.value})}/></label><label className="field"><span>Vínculo de dados</span><select className="input" value={current.binding??""} onChange={e=>patch({binding:e.target.value||undefined})}><option value="">Sem vínculo</option>{visualBindings.map(binding=><option key={binding} value={binding}>{binding}</option>)}</select></label><label className="field"><span>Tamanho da fonte</span><input className="input" type="number" min="8" max="500" value={current.textStyle?.fontSize??32} onChange={e=>patch({textStyle:{...current.textStyle,fontSize:Number(e.target.value)}})}/></label><label className="field"><span>Cor</span><input className="input" type="color" value={current.textStyle?.color??"#111111"} onChange={e=>patch({textStyle:{...current.textStyle,color:e.target.value}})}/></label></>}
  </div>:<p className="muted">Selecione um elemento.</p>}</aside>
 </div>
}
